version: 2
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
