version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    ignored_updates:
      - match:
          dependency_name: "flow-bin"
    version_requirement_updates: "widen_ranges"



#version: 2
#update_configs:
#  - package_manager: "javascript"
#    directory: "/"
#    update_schedule: "live"
#update_configs:
#  - package_manager: "docker"
#    directory: "/"
#    update_schedule: "weekly"
